# config.py
SHORTS_WIDTH = 1080
SHORTS_HEIGHT = 1920
TARGET_FPS = 30

# Whisper 음성인식 모델 설정
WHISPER_MODEL_NAME = "small"

HOOK_MIN_DURATION = 2.0
HOOK_MAX_DURATION = 5.0

MIN_HIGHLIGHT_DURATION = 2.0
MAX_HIGHLIGHT_DURATION = 8.0
CONTEXT_PADDING_BEFORE = 1.2
CONTEXT_PADDING_AFTER = 2.0
HIGHLIGHT_THRESHOLD = 0.75

ENABLE_HOOK = True
ENABLE_HIGHLIGHT_REPLAY = True
ENABLE_COMMENTS = True

COMMENT_DELAY_AFTER_EVENT = 0.5
COMMENT_MAX_DURATION = 3.2
COMMENT_RELEVANCE_THRESHOLD = 0.70

TARGET_SHORTS_DURATION = 60.0
MAX_WORDS_PER_SUBTITLE = 4
MAX_CHARS_PER_SUBTITLE = 16

DEFAULT_YOUTUBE_API_KEY = "AIzaSyAcMm3MsrdaHGL3rvRkKgSkDtNLxgPVC3A"